# Texture and pattern recognition in images

In [1]:
import cv2
from skimage import feature
from imutils import paths
import numpy as np

#### LBP Calculation 

In [2]:
class LocalBinaryPatterns:
    
    def __init__(self, numPoints, radius):

        self.numPoints = numPoints
        self.radius = radius
        
    def describe(self, image, eps=1e-7):

        lbp = feature.local_binary_pattern(image, self.numPoints, self.radius, method="uniform")
        
        (hist, _) = np.histogram(lbp.ravel(), bins=np.arange(0, self.numPoints + 3), range=(0, self.numPoints + 2))

        hist = hist.astype("float")
        hist /= (hist.sum() + eps)

        return hist

In [3]:
desc = LocalBinaryPatterns(24, 8)

In [4]:
train = []

for imagePath in paths.list_images("D:\PYTHON\MACHINE LEARNING\PROJECTS\Classification Of Images\Train") :

    image = cv2.imread(imagePath)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    hist = desc.describe(gray)

    train.append(hist)

    print("Processed" ,  len(train) , "training images")

Processed 1 training images
Processed 2 training images
Processed 3 training images
Processed 4 training images
Processed 5 training images
Processed 6 training images
Processed 7 training images
Processed 8 training images
Processed 9 training images
Processed 10 training images
Processed 11 training images
Processed 12 training images


In [5]:
test = []

for imagePath in paths.list_images("D:\PYTHON\MACHINE LEARNING\PROJECTS\Classification Of Images\Test") :

    image = cv2.imread(imagePath)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    hist = desc.describe(gray)

    test.append(hist)

    print("Processed" ,  len(test) , "test images")

Processed 1 test images
Processed 2 test images
Processed 3 test images


In [6]:
test

[array([0.03601667, 0.02943108, 0.00657042, 0.00410833, 0.00321175,
        0.00296333, 0.00287033, 0.00333233, 0.00439117, 0.00703733,
        0.012918  , 0.03025025, 0.05162292, 0.03306233, 0.01385892,
        0.00752117, 0.00458317, 0.0034645 , 0.00257883, 0.002524  ,
        0.00258075, 0.00330225, 0.00610917, 0.03576367, 0.04509358,
        0.64483375]),
 array([0.02083192, 0.01527892, 0.01076583, 0.0099625 , 0.00959667,
        0.011377  , 0.01275083, 0.01617767, 0.01870392, 0.02323017,
        0.02648075, 0.031127  , 0.031788  , 0.03293958, 0.02883408,
        0.02614642, 0.02175608, 0.019597  , 0.01623758, 0.01539008,
        0.01363417, 0.014505  , 0.01668142, 0.02118958, 0.03613667,
        0.49888117]),
 array([0.01258917, 0.00728692, 0.00788183, 0.00942708, 0.01117592,
        0.01434883, 0.01829492, 0.025311  , 0.03396325, 0.047944  ,
        0.07018258, 0.10022142, 0.10941767, 0.07318067, 0.04395642,
        0.03144767, 0.02468658, 0.02112392, 0.01803317, 0.01588183,
    

In [7]:
train[11]

array([0.00669558, 0.00436008, 0.00392542, 0.0047165 , 0.00586733,
       0.00873667, 0.012996  , 0.02180083, 0.03453217, 0.05636542,
       0.08671542, 0.12400033, 0.131684  , 0.09499042, 0.05895283,
       0.03981808, 0.02848125, 0.02140383, 0.01584042, 0.01197842,
       0.00867308, 0.00693267, 0.00664033, 0.00679867, 0.0109615 ,
       0.18613275])

#### Assigning labels and sampling

In [8]:
import pandas as pd

In [9]:
data = pd.DataFrame(train)

data['Labels'] = np.zeros(len(train))

for i in range(0 , 4) :
    data.iloc[i, 26] = 1.0  

for i in range(4 , 8) :
    data.iloc[i, 26] = 2.0 
    
for i in range(8 , 12) :
    data.iloc[i, 26] = 3.0 
    
data = data.sample(frac = 1)

data

0         1         2         3         4         5         6  \
3   0.022189  0.015036  0.009268  0.008000  0.006355  0.006499  0.006078   
4   0.033461  0.015923  0.013940  0.014122  0.013718  0.014406  0.015031   
10  0.006936  0.004488  0.004330  0.005221  0.006723  0.010086  0.014668   
5   0.035146  0.016786  0.014753  0.014168  0.013423  0.013910  0.014229   
1   0.034668  0.028382  0.006958  0.003957  0.002878  0.002533  0.002473   
0   0.038142  0.030267  0.008047  0.004551  0.003001  0.002423  0.002222   
7   0.033126  0.022910  0.010268  0.008132  0.007388  0.007607  0.008101   
6   0.036871  0.022470  0.011878  0.009983  0.009302  0.009429  0.009843   
11  0.006696  0.004360  0.003925  0.004716  0.005867  0.008737  0.012996   
2   0.039303  0.030911  0.007599  0.004849  0.003763  0.003344  0.003039   
8   0.019281  0.010705  0.011183  0.012119  0.013979  0.017218  0.021138   
9   0.015190  0.007985  0.008660  0.010541  0.013036  0.016921  0.021455   

           7         8         9  ...        17        18        19        20  \
3   0.007244  0.007969  0.011765  ...  0.010779  0.008860  0.009847  0.009666   
4   0.017493  0.019725  0.024163  ...  0.019975  0.017287  0.016646  0.015694   
10  0.023339  0.035334  0.055260  ...  0.020425  0.015770  0.012474  0.009687   
5   0.016355  0.018508  0.023149  ...  0.018427  0.016042  0.015576  0.014894   
1   0.003156  0.004309  0.007207  ...  0.003654  0.002538  0.002434  0.002465   
0   0.002609  0.003582  0.005785  ...  0.002848  0.002198  0.002293  0.002697   
7   0.009307  0.011355  0.014588  ...  0.009923  0.008425  0.007916  0.007682   
6   0.011061  0.012774  0.015327  ...  0.012208  0.010854  0.010370  0.010106   
11  0.021801  0.034532  0.056365  ...  0.021404  0.015840  0.011978  0.008673   
2   0.003338  0.004150  0.006331  ...  0.003376  0.002696  0.002836  0.003095   
8   0.026878  0.033374  0.043235  ...  0.017883  0.015974  0.014969  0.013806   
9   0.028408  0.036683  0.049447  ...  0.020810  0.018320  0.016619  0.014545   

          21        22        23        24        25  Labels  
3   0.012580  0.016550  0.037986  0.059785  0.466513     1.0  
4   0.016118  0.016885  0.019446  0.040354  0.437505     2.0  
10  0.007889  0.007380  0.007401  0.012035  0.200728     3.0  
5   0.015741  0.017267  0.020027  0.040450  0.443305     2.0  
1   0.003250  0.006420  0.034811  0.042096  0.633913     1.0  
0   0.003966  0.008025  0.037435  0.047395  0.656431     1.0  
7   0.008389  0.010824  0.024723  0.034764  0.609870     2.0  
6   0.010806  0.012748  0.024338  0.038304  0.580647     2.0  
11  0.006933  0.006640  0.006799  0.010961  0.186133     3.0  
2   0.004187  0.007495  0.036819  0.048916  0.656554     1.0  
8   0.012848  0.013411  0.015202  0.023341  0.330944     3.0  
9   0.012669  0.011849  0.011757  0.019870  0.255959     3.0  

[12 rows x 27 columns]

In [10]:
x_train = data.drop('Labels' , axis = 1)
y_train = data.Labels

In [11]:
test_data = pd.DataFrame(test)

test_data['Labels'] = np.zeros(len(test))

for i in range(0 , 1) :
    test_data.iloc[i, 26] = 1.0  

for i in range(1 , 2) :
    test_data.iloc[i, 26] = 2.0 
    
for i in range(2 , 3) :
    test_data.iloc[i, 26] = 3.0 

test_data

0         1         2         3         4         5         6  \
0  0.036017  0.029431  0.006570  0.004108  0.003212  0.002963  0.002870   
1  0.020832  0.015279  0.010766  0.009962  0.009597  0.011377  0.012751   
2  0.012589  0.007287  0.007882  0.009427  0.011176  0.014349  0.018295   

          7         8         9  ...        17        18        19        20  \
0  0.003332  0.004391  0.007037  ...  0.003464  0.002579  0.002524  0.002581   
1  0.016178  0.018704  0.023230  ...  0.019597  0.016238  0.015390  0.013634   
2  0.025311  0.033963  0.047944  ...  0.021124  0.018033  0.015882  0.013453   

         21        22        23        24        25  Labels  
0  0.003302  0.006109  0.035764  0.045094  0.644834     1.0  
1  0.014505  0.016681  0.021190  0.036137  0.498881     2.0  
2  0.011552  0.010827  0.010527  0.018471  0.238816     3.0  

[3 rows x 27 columns]

In [12]:
x_test = test_data.drop('Labels' , axis = 1)
y_test = test_data.Labels

In [13]:
y_test

0    1.0
1    2.0
2    3.0
Name: Labels, dtype: float64

### Training the model

In [14]:
from sklearn.svm import LinearSVC

model = LinearSVC( C=100.0 , random_state = 42 )

model.fit(x_train , y_train)

D:\ANACONDA\lib\site-packages\sklearn\svm\_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LinearSVC(C=100.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=42, tol=0.0001,
          verbose=0)

### Prediction

In [15]:
prediction = model.predict(x_test)
prediction

array([1., 2., 3.])

In [16]:
pred_data = pd.DataFrame(prediction)

pred_data[''] = pd.DataFrame(y_test)

pred_data.columns = ['Predicted' , 'Actual']

pred_data

Predicted  Actual
0        1.0     1.0
1        2.0     2.0
2        3.0     3.0

In [17]:
prediction_1 = model.predict(test[0].reshape(1, -1))
prediction_1

array([1.])

In [18]:
images = []

for imagePath in paths.list_images("D:\PYTHON\MACHINE LEARNING\PROJECTS\Classification Of Images\Test") :

    image = cv2.imread(imagePath)
    
    images.append(image)

In [19]:
def prediction(test) :
    
        
    pred = model.predict(test)
    
    if(pred == 1) :
    
        print('Keyboard')
    
    if(pred == 2) :
    
        print('Floor')
        
    if(pred == 3) :
    
        print('Mat')
    
    
    cv2.imshow("Image" , images[0])
    cv2.waitKey(0)
    

In [20]:
prediction(test[0].reshape(1, -1))

Keyboard
